[package]
name = "rs-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
aws-sdk-dynamodb = "1.89.0"
aws_lambda_events = "0.17.0"
base64 = "0.22.1"
hex = "0.4.3"
lambda_http = "0.16.0"
lambda_runtime = "0.14.3"
openssl = "0.10.73"
postgres = "0.19.10"
postgres-openssl = "0.5.1"
reqwest = "0.12.23"
serde = "1.0.219"
serde_json = "1.0.143"
sodiumoxide = "0.2.7"
thiserror = "2.0.16"
tokio = "1.48.0"
